import { useEffect, useMemo, useRef, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { detectRun, getAvailableModels, getHealth, getRun } from '../services/api'
import { EXAMPLE_QUESTIONS } from '../data/exampleQuestions'
import { AnswerCard } from '../components/detect/AnswerCard'
import {
  AnalysisProgress,
  type ProgressStepItem,
  type StepState,
} from '../components/detect/AnalysisProgress'
import { AnalysisSummary } from '../components/detect/AnalysisSummary'
import { MethodOverview } from '../components/detect/MethodOverview'
import { MutationTabs } from '../components/detect/MutationTabs'
import { QuestionInput } from '../components/detect/QuestionInput'
import { ScoreCard } from '../components/detect/ScoreCard'
import { EmptyState, ErrorState, LoadingState } from '../components/ui/Status'
import type { AnalysisResult, AnalysisStage, AnswerModelOption } from '../types'
import {
  AnalysisStage as Stage,
  RunStatus,
  analysisStillRunning,
  isAnalysisFailureStatus,
  isWebEvidenceTerminal,
} from '../types'
import { formatModelDisplay, formatProviderDisplay } from '../lib/format'
import { WebEvidencePanel } from '../components/detect/WebEvidencePanel'
import { VerificationSummaryPanel } from '../components/detect/VerificationSummaryPanel'

function ActiveProviderStatus({
  provider,
  model,
  geminiVerifierModel,
}: {
  provider: string | null
  model: string | null
  geminiVerifierModel: string | null
}) {
  const displayModel = formatModelDisplay(model) ?? model ?? 'Gemma 4:26B'
  const displayProvider = formatProviderDisplay(provider, model ?? undefined) || 'Ollama'
  const verifierModel = formatModelDisplay(geminiVerifierModel) ?? geminiVerifierModel ?? 'Gemini 3.8 Flash'

  return (
    <div className="mt-3 space-y-1">
      <p className="flex items-center gap-2 text-xs text-ink-muted">
        <span className="h-1.5 w-1.5 rounded-full bg-accent" aria-hidden="true" />
        <span>
          Generated by {displayProvider}
          <span className="mx-1.5 text-line-strong">·</span>
          {displayModel}
        </span>
      </p>
      <p className="flex items-center gap-2 text-xs text-ink-muted">
        <span className="h-1.5 w-1.5 rounded-full bg-[hsl(210,80%,60%)]" aria-hidden="true" />
        <span>
          MetaQA verified by Google Gemini
          <span className="mx-1.5 text-line-strong">·</span>
          {verifierModel}
        </span>
      </p>
      <p className="flex items-center gap-2 text-xs text-ink-muted">
        <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" aria-hidden="true" />
        <span>Web evidence checked independently via Tavily</span>
      </p>
    </div>
  )
}

function stageFromRunStatus(status: AnalysisResult['status']): AnalysisStage {
  if (status === RunStatus.Completed) return Stage.Complete
  if (isAnalysisFailureStatus(status)) return Stage.AnalysisFailed
  if (status === RunStatus.VerifyingMutations || status === RunStatus.MutationsReady) {
    return Stage.VerifyingMutations
  }
  if (status === RunStatus.CalculatingScore) return Stage.CalculatingScore
  if (status === RunStatus.AnswerReady) return Stage.AnswerReady
  return Stage.GeneratingMutations
}

function shouldKeepPolling(analysis: AnalysisResult): boolean {
  // Never stop solely because MetaQA failed — Web Evidence may still be running.
  return analysisStillRunning(analysis)
}

function metaqaFailureMessage(result: AnalysisResult | null, mutationsVisible: boolean): string {
  if (!result) return 'MetaQA analysis failed.'
  const fromServer = result.analysisError?.trim()
  if (fromServer) return fromServer
  if (result.status === RunStatus.VerificationFailed || mutationsVisible) {
    return 'Mutation verification failed. The generated answer and existing mutations are still available.'
  }
  if (result.status === RunStatus.ScoringFailed) {
    return 'MetaQA could not finish calculating the score.'
  }
  return 'MetaQA could not generate the required mutation tests.'
}

function getMetaqaSteps(
  stage: AnalysisStage,
  status: RunStatus | undefined,
  mutationsCount: number,
  verifiedCount: number,
  metaqaFailed: boolean,
): ProgressStepItem[] {
  const isComplete = status === RunStatus.Completed || stage === Stage.Complete
  const isScoring = stage === Stage.CalculatingScore || status === RunStatus.CalculatingScore
  const isVerifying =
    stage === Stage.VerifyingMutations ||
    status === RunStatus.VerifyingMutations ||
    status === RunStatus.MutationsReady ||
    (mutationsCount > 0 && verifiedCount < mutationsCount && !isScoring && !isComplete && !metaqaFailed)
  const isMutationsGenerating =
    stage === Stage.GeneratingMutations ||
    stage === Stage.AnswerReady ||
    status === RunStatus.GeneratingMutations

  // 1. Creating test mutations
  let s1: StepState = 'pending'
  if (mutationsCount > 0 || isVerifying || isScoring || isComplete) {
    s1 = 'done'
  } else if (isMutationsGenerating) {
    s1 = 'active'
  } else if (metaqaFailed && mutationsCount === 0) {
    s1 = 'failed'
  }

  // 2. Verifying mutations
  let s2: StepState = 'pending'
  if (isComplete || isScoring || (mutationsCount > 0 && verifiedCount >= mutationsCount)) {
    s2 = 'done'
  } else if (isVerifying) {
    s2 = 'active'
  } else if (metaqaFailed && mutationsCount > 0 && verifiedCount < mutationsCount) {
    s2 = 'failed'
  }

  // 3. Calculating score
  let s3: StepState = 'pending'
  if (isComplete) {
    s3 = 'done'
  } else if (isScoring) {
    s3 = 'active'
  } else if (metaqaFailed && status === RunStatus.ScoringFailed) {
    s3 = 'failed'
  }

  // 4. MetaQA analysis complete
  let s4: StepState = 'pending'
  if (isComplete) {
    s4 = 'done'
  }

  const verifyLabel =
    isVerifying && mutationsCount > 0
      ? `Verifying mutations (${verifiedCount}/${mutationsCount})`
      : s2 === 'done' && mutationsCount > 0
        ? `Verifying mutations (${mutationsCount}/${mutationsCount})`
        : 'Verifying mutations'

  return [
    { id: 'mutations', label: 'Creating test mutations', state: s1 },
    { id: 'verify', label: verifyLabel, state: s2 },
    { id: 'score', label: 'Calculating MetaQA score', state: s3 },
    { id: 'complete', label: 'MetaQA analysis complete', state: s4 },
  ]
}

function getMetaqaStatus(
  stage: AnalysisStage,
  resultStatus: RunStatus | undefined,
  metaqaFailed: boolean,
): 'running' | 'completed' | 'failed' | 'unavailable' | 'pending' {
  if (resultStatus === RunStatus.Completed || stage === Stage.Complete) return 'completed'
  if (metaqaFailed) return 'unavailable'
  if (
    stage === Stage.AnswerReady ||
    stage === Stage.GeneratingMutations ||
    stage === Stage.VerifyingMutations ||
    stage === Stage.CalculatingScore ||
    resultStatus === RunStatus.GeneratingMutations ||
    resultStatus === RunStatus.VerifyingMutations ||
    resultStatus === RunStatus.MutationsReady ||
    resultStatus === RunStatus.CalculatingScore
  ) {
    return 'running'
  }
  return 'pending'
}

export function DetectPage() {
  const [params, setParams] = useSearchParams()
  const runId = params.get('id')
  const requestToken = useRef(0)
  const submitOwnsPolling = useRef(false)

  const [question, setQuestion] = useState('')
  const [result, setResult] = useState<AnalysisResult | null>(null)
  const [stage, setStage] = useState<AnalysisStage>(Stage.Idle)
  const [error, setError] = useState<string | null>(null)
  const [fetching, setFetching] = useState(Boolean(runId))
  const [provider, setProvider] = useState<string | null>(null)
  const [healthGenerator, setHealthGenerator] = useState<string | null>(null)
  const [geminiVerifierModel, setGeminiVerifierModel] = useState<string | null>(null)
  const [selectedAnswerModel, setSelectedAnswerModel] = useState('gemma')
  const [availableModels, setAvailableModels] = useState<AnswerModelOption[]>([
    { id: 'gemma', name: 'Gemma 4:26B', provider: 'ollama', providerDisplay: 'Ollama Cloud', modelName: 'gemma4:26b', configured: true, isDefault: true },
    { id: 'glm', name: 'GLM-4.7-Flash', provider: 'cloudflare', providerDisplay: 'Cloudflare Workers AI', modelName: '@cf/zai-org/glm-4.7-flash', configured: false, isDefault: false },
    { id: 'qwen', name: 'Qwen', provider: 'groq', providerDisplay: 'Alibaba / Groq', modelName: 'qwen-2.5-32b', configured: false, isDefault: false },
    { id: 'openrouter', name: 'OpenRouter', provider: 'openrouter', providerDisplay: 'OpenRouter', modelName: 'liquid/lfm-2.5-2.6b:free', configured: false, isDefault: false },
    { id: 'gemini', name: 'Gemini Flash 3.8', provider: 'gemini', providerDisplay: 'Google', modelName: 'gemini-3.8-flash', configured: true, isDefault: false },
  ])

  useEffect(() => {
    void getAvailableModels()
      .then((models) => {
        if (models && models.length > 0) {
          setAvailableModels(models)
        }
      })
      .catch(() => {})
  }, [])

  useEffect(() => {
    void getHealth()
      .then((h) => {
        setProvider(h.llm_provider ?? null)
        setHealthGenerator(h.generator_model ?? null)
        setGeminiVerifierModel(
          h.gemini_verifier_model ||
            (h.gemini_verifier_ready ? (h.gemini_verifier_model ?? null) : null) ||
            h.verifier_model ||
            null,
        )
      })
      .catch(() => {})
  }, [])

  const waitingForAnswer = stage === Stage.GeneratingAnswer
  const metaqaRunning =
    stage === Stage.AnswerReady ||
    stage === Stage.GeneratingMutations ||
    stage === Stage.VerifyingMutations ||
    stage === Stage.CalculatingScore
  const webEvidenceRunning =
    Boolean(result) && !isWebEvidenceTerminal(result?.webEvidence?.status)
  const analyzing = metaqaRunning || webEvidenceRunning
  const inputLocked = waitingForAnswer || analyzing

  // Answer is independent of MetaQA / Web Evidence success — show whenever we have text.
  const answerReady = useMemo(
    () => Boolean(result?.answer?.trim()) && stage !== Stage.GeneratingAnswer,
    [result, stage],
  )

  useEffect(() => {
    if (!runId) return
    if (submitOwnsPolling.current) return
    let cancelled = false
    let pollTimer: number | undefined
    setFetching(true)

    async function loadAndMaybePoll(id: string) {
      try {
        const analysis = await getRun(id)
        if (cancelled) return
        if (!analysis) {
          setFetching(false)
          setError(
            'That analysis could not be found. It may have been deleted, or the id in the URL is invalid.',
          )
          setResult(null)
          return
        }

        setQuestion(analysis.question)
        setResult(analysis)
        if (analysis.answerModel?.id) {
          setSelectedAnswerModel(analysis.answerModel.id)
        }
        setError(null)
        setFetching(false)
        setStage(stageFromRunStatus(analysis.status))

        if (!shouldKeepPolling(analysis)) {
          return
        }

        const poll = async () => {
          if (cancelled || submitOwnsPolling.current) return
          try {
            const next = await getRun(id)
            if (cancelled || !next) return
            setResult(next)
            setStage(stageFromRunStatus(next.status))
            if (!shouldKeepPolling(next)) {
              return
            }
            pollTimer = window.setTimeout(() => {
              void poll()
            }, 1200)
          } catch (err) {
            if (cancelled) return
            setError(err instanceof Error ? err.message : 'Unable to refresh analysis status.')
          }
        }

        pollTimer = window.setTimeout(() => {
          void poll()
        }, 1200)
      } catch (err) {
        if (cancelled) return
        setFetching(false)
        setError(err instanceof Error ? err.message : 'Unable to load that analysis from the server.')
      }
    }

    void loadAndMaybePoll(runId)
    return () => {
      cancelled = true
      if (pollTimer) window.clearTimeout(pollTimer)
    }
  }, [runId])

  async function handleAnalyze() {
    const token = ++requestToken.current
    submitOwnsPolling.current = true
    setError(null)
    setResult(null)
    setStage(Stage.GeneratingAnswer)
    try {
      const analysis = await detectRun(question, {
        answerModel: selectedAnswerModel,
        onStage: (next) => {
          if (requestToken.current !== token) return
          setStage(next)
        },
        onPartialResult: (partial) => {
          if (requestToken.current !== token) return
          setResult(partial)
          setParams({ id: partial.id }, { replace: true })
        },
      })
      if (requestToken.current !== token) return
      setResult(analysis)
      setParams({ id: analysis.id }, { replace: true })
      if (isAnalysisFailureStatus(analysis.status)) {
        setStage(Stage.AnalysisFailed)
        setError(null)
      } else {
        setStage(Stage.Complete)
      }
    } catch (err) {
      if (requestToken.current !== token) return
      setError(err instanceof Error ? err.message : 'Analysis failed. Please try again.')
      setStage((current) => {
        // Keep the answer card if verification failed after the answer was already shown.
        if (
          current === Stage.AnswerReady ||
          current === Stage.GeneratingMutations ||
          current === Stage.VerifyingMutations ||
          current === Stage.CalculatingScore ||
          current === Stage.AnalysisFailed
        ) {
          return Stage.AnalysisFailed
        }
        return Stage.Error
      })
    } finally {
      if (requestToken.current === token) {
        submitOwnsPolling.current = false
      }
    }
  }

  function handleReset() {
    requestToken.current += 1
    submitOwnsPolling.current = false
    setResult(null)
    setError(null)
    setStage(Stage.Idle)
    setFetching(false)
    setParams({}, { replace: true })
  }

  const activeModel = result?.model ?? healthGenerator
  const analysisComplete = result?.status === RunStatus.Completed
  const metaqaFailed =
    isAnalysisFailureStatus(result?.status) ||
    stage === Stage.AnalysisFailed ||
    (stage === Stage.Error && Boolean(result?.answer?.trim()))
  const mutations = result?.mutations ?? []
  const mutationsVisible = mutations.length > 0
  const verifiedCount = mutations.filter((item) => item.verified).length
  const verifyingMutations =
    stage === Stage.VerifyingMutations ||
    (metaqaRunning && mutationsVisible && stage !== Stage.CalculatingScore && verifiedCount < mutations.length)
  const showPageLevelError = Boolean(error) && !answerReady

  const metaqaSteps = getMetaqaSteps(stage, result?.status, mutations.length, verifiedCount, metaqaFailed)
  const metaqaProgressStatus = getMetaqaStatus(stage, result?.status, metaqaFailed)
  const metaqaErrorReason = metaqaFailed ? metaqaFailureMessage(result, mutationsVisible) : null

  const selectedModelOption = availableModels.find((m) => m.id === selectedAnswerModel)

  return (
    <div className="mx-auto max-w-3xl">
      <header className="mb-6">
        <p className="text-meta">VeriFact</p>
        <h1 className="mt-2 text-[1.75rem] font-semibold tracking-tight text-ink sm:text-[1.95rem]">
          AI Hallucination Detection
        </h1>
        <p className="mt-1 text-sm text-ink-secondary">
          VeriFact checks AI-generated answers using MetaQA and relevant web evidence.
        </p>
        <ActiveProviderStatus provider={provider} model={activeModel} geminiVerifierModel={geminiVerifierModel} />
      </header>

      <MethodOverview />

      <QuestionInput
        value={question}
        onChange={setQuestion}
        onSubmit={() => void handleAnalyze()}
        loading={inputLocked}
        disabled={inputLocked}
        models={availableModels}
        selectedModelId={selectedAnswerModel}
        onSelectModel={setSelectedAnswerModel}
      />

      {!result && !waitingForAnswer && !analyzing ? (
        <div className="mt-3 flex flex-wrap gap-2">
          {EXAMPLE_QUESTIONS.map((example) => (
            <button
              key={example}
              type="button"
              onClick={() => setQuestion(example)}
              className="rounded-full border border-line bg-surface px-3 py-1 text-xs text-ink-secondary hover:border-line-strong hover:text-ink"
            >
              {example}
            </button>
          ))}
        </div>
      ) : null}

      <div className="mt-8 space-y-8">
        {/* State 1: Answer is generating (neutral state, separate from MetaQA) */}
        {waitingForAnswer && !result ? (
          <AnswerCard
            isGenerating
            model={activeModel ?? undefined}
            answerModel={selectedModelOption ? {
              id: selectedModelOption.id,
              name: selectedModelOption.name,
              provider: selectedModelOption.providerDisplay || selectedModelOption.provider,
              modelName: selectedModelOption.modelName,
            } : undefined}
          />
        ) : null}

        {fetching && !waitingForAnswer && !analyzing && !result ? (
          <LoadingState label="Loading analysis…" />
        ) : null}

        {showPageLevelError ? (
          <ErrorState message={error ?? 'Request failed.'} onRetry={() => void handleAnalyze()} />
        ) : null}

        {!waitingForAnswer && !fetching && !error && !result && stage === Stage.Idle ? (
          <EmptyState
            title="No analysis yet"
            description="Enter a factual question. VeriFact will show the AI answer first, then continue MetaQA and Web Evidence in parallel."
          />
        ) : null}

        {/* State 2: Answer is ready — show Answer card, then two independent sibling pipelines */}
        {result && answerReady ? (
          <div className="animate-fade-up space-y-8">
            {/* Step 2: AI Answer Card */}
            <AnswerCard
              answer={result.answer}
              model={result.model}
              answerModel={
                result.answerModel ||
                (selectedModelOption
                  ? {
                      id: selectedModelOption.id,
                      name: selectedModelOption.name,
                      provider: selectedModelOption.providerDisplay || selectedModelOption.provider,
                      modelName: selectedModelOption.modelName,
                    }
                  : undefined)
              }
              responseTimeMs={result.responseTimeMs}
            />

            {/* Step 3: MetaQA Analysis & Results (Single Column) */}
            <section className="space-y-6">
              <AnalysisProgress
                title="MetaQA Analysis"
                description="VeriFact creates controlled changes to the AI's answer and checks whether the model reacts consistently."
                status={metaqaProgressStatus}
                steps={metaqaSteps}
                errorReason={metaqaErrorReason}
              />

              {result.status === RunStatus.Completed &&
              result.analysisError?.toLowerCase().includes('partially completed') ? (
                <div className="rounded-[var(--radius-md)] border border-line bg-canvas px-4 py-3 text-xs leading-relaxed text-ink-secondary">
                  {result.analysisError}
                </div>
              ) : null}

              {mutationsVisible ? (
                <MutationTabs mutations={mutations} verifying={verifyingMutations} />
              ) : null}

              {analysisComplete && result.score != null && result.verdict ? (
                <>
                  <ScoreCard score={result.score} threshold={result.threshold} verdict={result.verdict} />
                  <AnalysisSummary result={result} />
                </>
              ) : null}
            </section>

            {/* Step 4: Web Evidence Analysis & Results (Single Column, directly below MetaQA) */}
            <section className="space-y-6">
              <WebEvidencePanel evidence={result.webEvidence} />
            </section>

            {/* Step 5: Verification Summary below both analysis pipelines */}
            {result.verificationSummary?.ready ? (
              <div className="border-t border-line pt-2">
                <VerificationSummaryPanel
                  summary={result.verificationSummary}
                  onFocusClaim={(claimId) => {
                    document.getElementById(`web-claim-${claimId}`)?.scrollIntoView({
                      behavior: 'smooth',
                      block: 'start',
                    })
                  }}
                />
              </div>
            ) : null}

            {!analyzing ? (
              <div className="pt-2 text-center sm:text-left">
                <button
                  type="button"
                  onClick={handleReset}
                  className="text-sm font-medium text-ink-secondary underline-offset-4 hover:text-ink hover:underline"
                >
                  ← Start a new analysis
                </button>
              </div>
            ) : null}
          </div>
        ) : null}
      </div>
    </div>
  )
}
