import { useState, useMemo } from 'react'
import { AlertCircle, Bot, ChevronDown, Search } from 'lucide-react'
import type { IndependentAiVerdict } from '../../types'
import { classNames } from '../../lib/format'
import { VerdictBadge } from './CollapsibleModelVerdicts'

interface IndependentVerdictsCardProps {
  verdicts?: IndependentAiVerdict[]
  answerModelName?: string
}

export function IndependentVerdictsCard({
  verdicts = [],
  answerModelName,
}: IndependentVerdictsCardProps) {
  const [isSectionExpanded, setIsSectionExpanded] = useState(false)
  const [expandedModelId, setExpandedModelId] = useState<string | null>(null)
  const [filterQuery, setFilterQuery] = useState('')

  const verdictCounts = useMemo(() => {
    let yes = 0
    let no = 0
    let notSure = 0
    let failed = 0
    let pendingCount = 0

    for (const v of verdicts) {
      const norm = (v.verdict || '').toUpperCase().trim()
      const isFailed = v.status === 'failed' || norm.startsWith('FAILED') || Boolean(v.error)
      if (isFailed) {
        failed += 1
      } else if (norm === 'YES') {
        yes += 1
      } else if (norm === 'NO') {
        no += 1
      } else if (norm === 'NOT SURE' || norm === 'NOT_SURE') {
        notSure += 1
      } else if (v.status === 'pending' || norm === 'PENDING') {
        pendingCount += 1
      }
    }

    return { yes, no, notSure, failed, pending: pendingCount }
  }, [verdicts])

  const totalModels = verdicts.length
  const verifiedCount = totalModels - verdictCounts.pending
  const compactSummaryText =
    verdictCounts.pending > 0 && verifiedCount < totalModels
      ? `${verifiedCount}/${totalModels} models verified`
      : `${totalModels} model${totalModels === 1 ? '' : 's'} verified`

  const verdictSummaryString = `YES: ${verdictCounts.yes} · NO: ${verdictCounts.no} · NOT SURE: ${verdictCounts.notSure} · FAILED: ${verdictCounts.failed}`

  const filteredVerdicts = useMemo(() => {
    if (!filterQuery.trim()) return verdicts
    const q = filterQuery.toLowerCase()
    return verdicts.filter(
      (v) =>
        (v.modelName && v.modelName.toLowerCase().includes(q)) ||
        (v.provider && v.provider.toLowerCase().includes(q)) ||
        (v.modelId && v.modelId.toLowerCase().includes(q)) ||
        (v.verdict && v.verdict.toLowerCase().includes(q)),
    )
  }, [verdicts, filterQuery])

  if (!verdicts || verdicts.length === 0) {
    return null
  }

  const toggleModel = (modelId: string) => {
    setExpandedModelId((curr) => (curr === modelId ? null : modelId))
  }

  return (
    <section className="panel p-4 sm:p-5 animate-fade-up">
      {/* Header bar with collapsible toggle */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-line/70 pb-3.5">
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <Bot className="h-4 w-4 text-ink-secondary shrink-0" />
            <h3 className="text-sm font-semibold uppercase tracking-wider text-ink">
              Independent AI Verdicts
            </h3>
          </div>
          <p className="mt-1 text-xs text-ink-muted">
            {answerModelName
              ? `Independent cloud models evaluated the answer generated by ${answerModelName}.`
              : 'Independent cloud models evaluated the generated answer.'}
          </p>
        </div>

        <button
          type="button"
          onClick={() => setIsSectionExpanded((prev) => !prev)}
          aria-expanded={isSectionExpanded}
          className="inline-flex items-center gap-2 rounded-lg border border-line bg-surface px-3 py-1.5 text-xs font-medium text-ink hover:bg-surface-muted/50 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent"
        >
          <span className="font-mono text-[11px] text-ink-secondary">
            {verdictSummaryString}
          </span>
          <ChevronDown
            className={classNames(
              'h-3.5 w-3.5 text-ink-muted transition-transform duration-200',
              isSectionExpanded ? 'rotate-180 text-accent' : '',
            )}
          />
        </button>
      </div>

      {/* Summary line */}
      <div className="mt-3 flex items-center justify-between text-xs text-ink-muted">
        <span>{compactSummaryText}</span>
        <button
          type="button"
          onClick={() => setIsSectionExpanded((prev) => !prev)}
          className="text-accent hover:underline text-[11px] font-medium"
        >
          {isSectionExpanded ? 'Collapse verifiers' : 'Expand verifiers'}
        </button>
      </div>

      {/* Expanded list of models */}
      {isSectionExpanded && (
        <div className="mt-3 space-y-3 pt-2 border-t border-line/40 animate-fade-in">
          {totalModels > 6 && (
            <div className="relative">
              <Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-ink-muted pointer-events-none" />
              <input
                type="text"
                placeholder={`Filter ${totalModels} models…`}
                value={filterQuery}
                onChange={(e) => setFilterQuery(e.target.value)}
                className="w-full pl-8 pr-3 py-1.5 text-xs rounded-md border border-line bg-surface text-ink placeholder:text-ink-muted focus:outline-none focus:border-accent"
              />
            </div>
          )}

          <div
            className={classNames(
              'grid gap-2',
              totalModels > 1 ? 'sm:grid-cols-2' : 'grid-cols-1',
              totalModels > 6 ? 'max-h-[500px] overflow-y-auto pr-1' : '',
            )}
          >
            {filteredVerdicts.map((item) => {
              const isEntryExpanded = expandedModelId === item.modelId
              const norm = (item.verdict || '').toUpperCase().trim()
              const isFailed = item.status === 'failed' || norm.startsWith('FAILED') || Boolean(item.error)

              return (
                <div
                  key={item.modelId}
                  className={classNames(
                    'rounded-lg border transition-all duration-150',
                    isEntryExpanded
                      ? 'border-accent/60 bg-surface shadow-xs ring-1 ring-accent/20'
                      : 'border-line bg-surface hover:border-line-strong hover:bg-surface-muted/20',
                  )}
                >
                  <button
                    type="button"
                    onClick={() => toggleModel(item.modelId)}
                    aria-expanded={isEntryExpanded}
                    className="w-full flex items-start justify-between gap-2.5 p-3 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent rounded-lg"
                  >
                    <div className="min-w-0 flex-1">
                      <div className="flex flex-wrap items-center gap-1.5">
                        <span className="font-semibold text-xs text-ink truncate">
                          {item.modelName}
                        </span>
                        <span className="text-[10px] text-ink-muted truncate">
                          · {item.provider}
                        </span>
                      </div>
                      <span className="text-[10px] text-ink-muted mt-0.5 block">
                        {isEntryExpanded ? 'Click to collapse explanation' : 'Click to expand explanation'}
                      </span>
                    </div>

                    <div className="flex items-center gap-2 shrink-0">
                      <VerdictBadge verdict={item.verdict} status={item.status} />
                      <ChevronDown
                        className={classNames(
                          'h-3.5 w-3.5 text-ink-muted transition-transform duration-200 shrink-0',
                          isEntryExpanded ? 'rotate-180 text-accent' : '',
                        )}
                      />
                    </div>
                  </button>

                  {isEntryExpanded && (
                    <div className="border-t border-line/50 px-3 py-3 space-y-2.5 bg-surface-muted/30 rounded-b-lg text-xs">
                      <div className="flex items-center justify-between gap-2">
                        <span className="text-[10px] font-bold uppercase tracking-wider text-ink-muted">
                          Verdict
                        </span>
                        <VerdictBadge verdict={item.verdict} status={item.status} />
                      </div>

                      {isFailed ? (
                        <div className="rounded-md border border-red-200 dark:border-red-900/40 bg-red-50/70 dark:bg-red-950/30 p-2.5 text-xs text-red-700 dark:text-red-300 space-y-1">
                          <div className="flex items-center gap-1 font-bold text-[10px] uppercase tracking-wider">
                            <AlertCircle className="h-3.5 w-3.5 shrink-0" />
                            <span>Error Explanation</span>
                          </div>
                          <p className="leading-relaxed font-mono text-[11px]">
                            {item.error || 'Verification request failed.'}
                          </p>
                        </div>
                      ) : (
                        <div className="space-y-1">
                          <span className="text-[10px] font-bold uppercase tracking-wider text-ink-muted block">
                            Rationale
                          </span>
                          {item.rationale && item.rationale.trim().length > 0 ? (
                            <p className="leading-relaxed text-ink text-xs italic bg-surface p-2.5 rounded-md border border-line/60">
                              &ldquo;{item.rationale.trim()}&rdquo;
                            </p>
                          ) : (
                            <p className="text-ink-muted text-xs italic bg-surface p-2.5 rounded-md border border-line/60">
                              No explanation was returned by this model.
                            </p>
                          )}
                        </div>
                      )}
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        </div>
      )}
    </section>
  )
}
